'use client';

import React, { useState, useMemo } from 'react';
import { useApp, TestCase } from '../store/AppContext';

type Language = 'java-selenium' | 'python-selenium' | 'python-pytest' | 'java-testng' | 'cypress';

const LANG_META: Record<Language, { label: string; icon: string; ext: string; color: string }> = {
    'java-selenium': { label: 'Java + Selenium', icon: '☕', ext: '.java', color: '#f89820' },
    'python-selenium': { label: 'Python + Selenium', icon: '🐍', ext: '.py', color: '#3776ab' },
    'python-pytest': { label: 'Python + Pytest', icon: '🐍', ext: '.py', color: '#0a9edc' },
    'java-testng': { label: 'Java + TestNG', icon: '☕', ext: '.java', color: '#c62a2a' },
    'cypress': { label: 'Cypress (JS)', icon: '🌲', ext: '.cy.js', color: '#04c38e' },
};

function toMethodName(title: string) {
    return 'test' + title
        .replace(/[^a-zA-Z0-9\s]/g, '')
        .split(' ')
        .filter(Boolean)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('')
        .slice(0, 50);
}

function toClassName(title: string) {
    return title
        .replace(/[^a-zA-Z0-9\s]/g, '')
        .split(' ')
        .filter(Boolean)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('')
        .slice(0, 40) + 'Test';
}

function generateJavaSelenium(tc: TestCase): string {
    const className = toClassName(tc.title);
    const methodName = toMethodName(tc.title);
    const steps = tc.steps.map((s, i) => `
        // Step ${i + 1}: ${s.action}
        // Expected: ${s.expectedResult}
        // TODO: Implement step ${i + 1}
        // driver.findElement(By.id("element-id")).click();`).join('\n');

    return `package com.qa.tests;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Duration;

/**
 * Test Case ID: ${tc.tcId}
 * Title: ${tc.title}
 * Priority: ${tc.priority}
 * Module: ${tc.module}
 * Generated by: QA Copilot
 */
public class ${className} {

    private WebDriver driver;
    private WebDriverWait wait;
    private static final String BASE_URL = System.getProperty("base.url", "https://your-app.com");

    @Before
    public void setUp() {
        // Setup ChromeDriver (ensure chromedriver is in PATH)
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        driver.get(BASE_URL);
    }

    @Test
    public void ${methodName}() throws Exception {
        // TC ID: ${tc.tcId}
        // Description: ${tc.description || tc.title}
        // Preconditions: ${tc.preconditions || 'None'}
${steps}

        // Final verification
        // TODO: Add assertions to verify the expected outcome
        // assertEquals("Expected value", actualValue);
    }

    @After
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
}
`;
}

function generatePythonSelenium(tc: TestCase): string {
    const className = toClassName(tc.title);
    const methodName = toMethodName(tc.title).charAt(0).toLowerCase() + toMethodName(tc.title).slice(1);
    const steps = tc.steps.map((s, i) => `        # Step ${i + 1}: ${s.action}
        # Expected: ${s.expectedResult}
        # TODO: Implement step ${i + 1}
        # self.driver.find_element(By.ID, "element-id").click()`).join('\n\n');

    return `"""
Test Case ID: ${tc.tcId}
Title: ${tc.title}
Priority: ${tc.priority}
Module: ${tc.module}
Generated by: QA Copilot
"""
import pytest
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options


class Test${className}:
    """
    ${tc.description || tc.title}
    Preconditions: ${tc.preconditions || 'None'}
    """

    @pytest.fixture(autouse=True)
    def setup_teardown(self):
        """Setup and teardown for each test"""
        chrome_options = Options()
        chrome_options.add_argument('--headless')
        self.driver = webdriver.Chrome(options=chrome_options)
        self.driver.maximize_window()
        self.wait = WebDriverWait(self.driver, 15)
        self.base_url = os.getenv('BASE_URL', 'https://your-app.com')
        self.driver.get(self.base_url)
        yield
        self.driver.quit()

    def test_${methodName.replace(/([A-Z])/g, '_$1').toLowerCase()}_tc_${tc.tcId.replace('-', '_').toLowerCase()}(self):
        """
        TC: ${tc.tcId} - ${tc.title}
        """
${steps}

        # Final verification
        # TODO: Add assertions to verify the expected outcome
        # assert "expected text" in self.driver.page_source
    `;
}

function generatePythonPytest(tc: TestCase): string {
    const fnName = 'test_' + tc.title
        .replace(/[^a-zA-Z0-9\s]/g, '')
        .split(' ').filter(Boolean)
        .map(w => w.toLowerCase())
        .join('_')
        .slice(0, 50);

    const steps = tc.steps.map((s, i) =>
        `    # Step ${i + 1}: ${s.action} \n    # Expected: ${s.expectedResult} \n    pass  # TODO: Implement`
    ).join('\n\n');

    return `"""
test_${tc.tcId.toLowerCase().replace('-', '_')}.py
TC ID: ${tc.tcId} | Priority: ${tc.priority} | Module: ${tc.module}
Generated by QA Copilot
"""
import pytest
    from selenium.webdriver.common.by import By


@pytest.mark.${tc.priority.toLowerCase()}
@pytest.mark.${tc.module.toLowerCase().replace(/\s+/g, '_') || 'functional'}
def ${fnName} (driver, base_url):
"""
    ${tc.title}
Preconditions: ${tc.preconditions || 'None'}
Tags: ${tc.tags.join(', ') || 'None'}
"""
driver.get(base_url)

${steps}
`;
}

function generateCypress(tc: TestCase): string {
    const desc = tc.title;
    const steps = tc.steps.map((s, i) =>
        `    // Step ${i + 1}: ${s.action}\n    // Expected: ${s.expectedResult}\n    // cy.get('[data-testid="element"]').click()\n`
    ).join('\n');

    return `/**
 * TC: ${tc.tcId} | Priority: ${tc.priority}
 * ${tc.description || tc.title}
 * Generated by QA Copilot
 */
describe('${tc.module || 'General'} - ${tc.tcId}', () => {
  beforeEach(() => {
    // Preconditions: ${tc.preconditions || 'None'}
    cy.visit(Cypress.env('BASE_URL') || '/')
  })

  it('${desc}', () => {
${steps}
    // TODO: Add assertions
    // cy.contains('Expected text').should('be.visible')
  })
})
`;
}

function generateCode(tc: TestCase, lang: Language): string {
    switch (lang) {
        case 'java-selenium': return generateJavaSelenium(tc);
        case 'python-selenium': return generatePythonSelenium(tc);
        case 'python-pytest': return generatePythonPytest(tc);
        case 'java-testng': return generateJavaSelenium(tc).replace('org.junit', 'org.testng').replace('@Before\n', '@BeforeMethod\n    ').replace('@After\n', '@AfterMethod\n    ').replace('@Test\n', '@Test(description = "' + tc.tcId + '")\n    ');
        case 'cypress': return generateCypress(tc);
        default: return '';
    }
}

export default function Automation() {
    const { state } = useApp();
    const [selectedLang, setSelectedLang] = useState<Language>('java-selenium');
    const [selectedTCId, setSelectedTCId] = useState<string>(state.testCases[0]?.id || '');
    const [filterFolder, setFilterFolder] = useState('');
    const [copied, setCopied] = useState(false);

    const filteredTCs = useMemo(() => {
        return state.testCases.filter(t => !filterFolder || t.folderId === filterFolder);
    }, [state.testCases, filterFolder]);

    const selectedTC = state.testCases.find(t => t.id === selectedTCId);
    const code = selectedTC ? generateCode(selectedTC, selectedLang) : '';

    const handleCopy = () => {
        if (!code) return;
        navigator.clipboard.writeText(code).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    const handleDownload = () => {
        if (!code || !selectedTC) return;
        const meta = LANG_META[selectedLang];
        const filename = toClassName(selectedTC.title) + meta.ext;
        const blob = new Blob([code], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = filename; a.click();
    };

    const handleDownloadAll = () => {
        const tcs = filterFolder ? filteredTCs : state.testCases;
        const meta = LANG_META[selectedLang];
        let allCode = '';
        tcs.forEach(tc => { allCode += generateCode(tc, selectedLang) + '\n\n// ' + '='.repeat(60) + '\n\n'; });
        const blob = new Blob([allCode], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `all-test-cases${meta.ext}`; a.click();
    };

    return (
        <div>
            <div className="page-header">
                <div>
                    <div className="page-title">Automation Export</div>
                    <div className="page-subtitle">Generate test automation skeletons from manual test cases</div>
                </div>
                <div className="page-header-actions">
                    <button className="btn btn-outline" onClick={handleDownloadAll} id="download-all-btn">📦 Download All ({filteredTCs.length})</button>
                    <button className="btn btn-primary" onClick={handleDownload} disabled={!selectedTC} id="download-single-btn">
                        📥 Download File
                    </button>
                </div>
            </div>

            {/* Language Selector */}
            <div className="card" style={{ marginBottom: 20 }}>
                <div className="card-title" style={{ marginBottom: 14, fontSize: 13 }}>Select Automation Framework</div>
                <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                    {(Object.entries(LANG_META) as [Language, typeof LANG_META[Language]][]).map(([key, meta]) => (
                        <button
                            key={key}
                            onClick={() => setSelectedLang(key)}
                            id={`lang-${key}`}
                            style={{
                                display: 'flex', alignItems: 'center', gap: 10, padding: '10px 18px',
                                background: selectedLang === key ? `${meta.color}20` : 'rgba(255,255,255,0.03)',
                                border: `1px solid ${selectedLang === key ? meta.color + '60' : 'var(--color-border)'}`,
                                borderRadius: 'var(--radius-md)', cursor: 'pointer', transition: 'all 0.15s',
                                color: selectedLang === key ? meta.color : 'var(--color-text-secondary)',
                                fontWeight: selectedLang === key ? 700 : 500, fontSize: 13,
                            }}>
                            <span style={{ fontSize: 20 }}>{meta.icon}</span>
                            <span>{meta.label}</span>
                            {selectedLang === key && <span style={{ fontSize: 10, background: meta.color, color: 'white', padding: '2px 6px', borderRadius: 999 }}>Active</span>}
                        </button>
                    ))}
                </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '300px 1fr', gap: 20 }}>
                {/* TC Selector */}
                <div className="card" style={{ height: 'fit-content' }}>
                    <div className="card-header">
                        <div className="card-title" style={{ fontSize: 13 }}>Select Test Case</div>
                    </div>
                    <div className="form-group">
                        <select className="form-select" style={{ fontSize: 12 }} value={filterFolder} onChange={e => setFilterFolder(e.target.value)}>
                            <option value="">All Folders</option>
                            {state.folders.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}
                        </select>
                    </div>
                    <div style={{ maxHeight: 500, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 4 }}>
                        {filteredTCs.map(tc => (
                            <button key={tc.id} onClick={() => setSelectedTCId(tc.id)}
                                style={{
                                    display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 4,
                                    padding: '8px 10px', borderRadius: 'var(--radius-sm)',
                                    background: selectedTCId === tc.id ? 'rgba(59,130,246,0.1)' : 'transparent',
                                    border: `1px solid ${selectedTCId === tc.id ? 'rgba(59,130,246,0.3)' : 'transparent'}`,
                                    cursor: 'pointer', transition: 'all 0.12s', textAlign: 'left',
                                    color: 'var(--color-text-primary)', width: '100%',
                                }}>
                                <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                                    <span style={{ fontSize: 10, fontFamily: 'monospace', color: 'var(--color-text-muted)' }}>{tc.tcId}</span>
                                    <span style={{ fontSize: 10, background: tc.automationStatus === 'Automated' ? 'rgba(16,185,129,0.1)' : 'rgba(255,255,255,0.05)', color: tc.automationStatus === 'Automated' ? 'var(--color-success)' : 'var(--color-text-muted)', padding: '1px 5px', borderRadius: 999 }}>
                                        {tc.automationStatus}
                                    </span>
                                </div>
                                <div style={{ fontSize: 12, lineHeight: 1.4, color: selectedTCId === tc.id ? 'var(--color-primary-light)' : 'var(--color-text-secondary)' }}>
                                    {tc.title.slice(0, 65)}{tc.title.length > 65 ? '…' : ''}
                                </div>
                            </button>
                        ))}
                        {filteredTCs.length === 0 && <div style={{ textAlign: 'center', padding: '20px', color: 'var(--color-text-muted)', fontSize: 12 }}>No test cases found</div>}
                    </div>
                </div>

                {/* Code Panel */}
                <div className="card" style={{ padding: 0 }}>
                    {selectedTC ? (
                        <>
                            <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--color-border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10 }}>
                                <div>
                                    <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 4 }}>
                                        <span style={{ fontSize: 16 }}>{LANG_META[selectedLang].icon}</span>
                                        <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--color-text-primary)' }}>
                                            {toClassName(selectedTC.title)}{LANG_META[selectedLang].ext}
                                        </span>
                                        <span className="badge badge-muted" style={{ fontFamily: 'monospace', fontSize: 10 }}>{selectedTC.tcId}</span>
                                    </div>
                                    <div style={{ fontSize: 12, color: 'var(--color-text-muted)' }}>{LANG_META[selectedLang].label} · {selectedTC.steps.length} steps</div>
                                </div>
                                <div style={{ display: 'flex', gap: 8 }}>
                                    <button className="btn btn-outline btn-sm" onClick={handleCopy} id="copy-code-btn">
                                        {copied ? '✅ Copied!' : '📋 Copy'}
                                    </button>
                                    <button className="btn btn-primary btn-sm" onClick={handleDownload}>📥 Download</button>
                                </div>
                            </div>
                            <div style={{ position: 'relative' }}>
                                <pre className="code-block" style={{ borderRadius: 0, margin: 0, maxHeight: '60vh', borderTop: 'none' }}>
                                    {code}
                                </pre>
                            </div>
                        </>
                    ) : (
                        <div className="empty-state" style={{ padding: '60px 40px' }}>
                            <div className="empty-state-icon">⚡</div>
                            <div className="empty-state-title">Select a test case</div>
                            <div className="empty-state-desc">Choose a test case from the list to generate its automation skeleton code</div>
                        </div>
                    )}
                </div>
            </div>

            {/* Info Cards */}
            <div className="grid-3" style={{ marginTop: 20 }}>
                <div className="card">
                    <div style={{ fontSize: 20, marginBottom: 8 }}>☕</div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--color-text-primary)', marginBottom: 4 }}>Java + Selenium/TestNG</div>
                    <div style={{ fontSize: 12, color: 'var(--color-text-muted)', lineHeight: 1.6 }}>
                        Generates JUnit/TestNG test classes with WebDriver setup. Best for enterprise Java projects.
                    </div>
                </div>
                <div className="card">
                    <div style={{ fontSize: 20, marginBottom: 8 }}>🐍</div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--color-text-primary)', marginBottom: 4 }}>Python + Selenium/Pytest</div>
                    <div style={{ fontSize: 12, color: 'var(--color-text-muted)', lineHeight: 1.6 }}>
                        Generates pytest-compatible scripts with fixtures. Ideal for Python automation frameworks.
                    </div>
                </div>
                <div className="card">
                    <div style={{ fontSize: 20, marginBottom: 8 }}>🌲</div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--color-text-primary)', marginBottom: 4 }}>Cypress (JavaScript)</div>
                    <div style={{ fontSize: 12, color: 'var(--color-text-muted)', lineHeight: 1.6 }}>
                        Generates Cypress spec files. Perfect for modern web apps with fast E2E testing.
                    </div>
                </div>
            </div>
        </div>
    );
}
